import { IGuest } from "../../../interface/user";

export const guestHelpers = {
  users: [
    {
      id: 1,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "active",
    },
    {
      id: 2,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "Inactive",
    },
    {
      id: 3,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "active",
    },
    {
      id: 4,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "Inactive",
    },
    {
      id: 5,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "active",
    },
    {
      id: 6,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "Inactive",
    },
    {
      id: 7,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "active",
    },
    {
      id: 8,
      name: "chinonso",
      dateOrder: 30,
      room: 33,
      checkIn: "software enigneer",
      checkOut: "Go",
      status: "Inactive",
    },
  ] as unknown as IGuest,
  usersHeaders: [
    "Guest",
    "Date Order",
    "Room",
    "Check In",
    "Check Out",
    "Status",
  ],
};
